const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Timeline,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Shape3D,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Behaviors.wrap,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{ControladorDaTimeline: 0},
	{Dragão: 0},
	{MenuPlanoDeFundo: 0},
	{EntradaDeTexto: 0},
	{Mouse: 0},
	{Forma3D: 0},
	{Play: 0},
	{Teclado: 0},
	{Sólido: 0},
	{chao: 0},
	{balão: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Mago: 0},
	{EpilogoPlanoDeFundo: 0},
	{SensorSolido: 0},
	{Jogador_Dialogo: 0},
	{CaixaDeDialogo: 0},
	{FonteDeSprites: 0},
	{BalaoDeFala1: 0},
	{BalaoDeFala2: 0},
	{Sprite: 0},
	{NameGame: 0},
	{Texto: 0},
	{Exit: 0},
	{Navegador: 0},
	{DarAVolta: 0},
	{FlorestaPlanoDeFundo: 0},
	{Sprite2: 0},
	{Fixar: 0},
	{CentrarEm: 0},
	{RedDragon: 0},
	{Sprite3: 0},
	{Física: 0},
	{Dragao_Sensor: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite6: 0}
];

self.InstanceType = {
	ControladorDaTimeline: class extends self.IInstance {},
	Dragão: class extends self.ISpriteInstance {},
	MenuPlanoDeFundo: class extends self.ITiledBackgroundInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Mouse: class extends self.IInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	Play: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	chao: class extends self.ISpriteInstance {},
	Mago: class extends self.ISpriteInstance {},
	EpilogoPlanoDeFundo: class extends self.ITiledBackgroundInstance {},
	SensorSolido: class extends self.ISpriteInstance {},
	Jogador_Dialogo: class extends self.ISpriteInstance {},
	CaixaDeDialogo: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	BalaoDeFala1: class extends self.ISpriteInstance {},
	BalaoDeFala2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	NameGame: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Exit: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	FlorestaPlanoDeFundo: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	RedDragon: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Dragao_Sensor: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {}
}